INSERT INTO tb_category(name) VALUES ('Books');
INSERT INTO tb_category(name) VALUES ('Electronics');
INSERT INTO tb_category(name) VALUES ('Computers');
INSERT INTO tb_category(name) VALUES ('Furniture');
INSERT INTO tb_category(name) VALUES ('Jewelry');
INSERT INTO tb_category(name) VALUES ('Art & Craft');
INSERT INTO tb_category(name) VALUES ('Travel & Adventure');
INSERT INTO tb_category(name) VALUES ('Fitness & Exercise');
INSERT INTO tb_category(name) VALUES ('Garden Tools');
INSERT INTO tb_category(name) VALUES ('Beauty & Personal Care');
INSERT INTO tb_category(name) VALUES ('Electrical Appliances');
INSERT INTO tb_category(name) VALUES ('Outdoor Furniture');
INSERT INTO tb_category(name) VALUES ('Mobile Accessories');
INSERT INTO tb_category(name) VALUES ('Clothing');
INSERT INTO tb_category(name) VALUES ('Home & Garden');
INSERT INTO tb_category(name) VALUES ('Sports & Outdoors');
INSERT INTO tb_category(name) VALUES ('Toys & Games');
INSERT INTO tb_category(name) VALUES ('Health & Beauty');
INSERT INTO tb_category(name) VALUES ('Automotive');
INSERT INTO tb_category(name) VALUES ('Movies & TV Shows');
INSERT INTO tb_category(name) VALUES ('Music');
INSERT INTO tb_category(name) VALUES ('Food & Beverages');
INSERT INTO tb_category(name) VALUES ('Pet Supplies');
INSERT INTO tb_category(name) VALUES ('Baby & Kids');
INSERT INTO tb_category(name) VALUES ('Vintage & Antiques');
INSERT INTO tb_category(name) VALUES ('Stationery');
INSERT INTO tb_category(name) VALUES ('Photography');
INSERT INTO tb_category(name) VALUES ('Fitness Wearables');
INSERT INTO tb_category(name) VALUES ('Gourmet Foods');
INSERT INTO tb_category(name) VALUES ('DIY & Home Improvement');
INSERT INTO tb_category(name) VALUES ('Electronic Gadgets');
INSERT INTO tb_category(name) VALUES ('Artificial Intelligence');
INSERT INTO tb_category(name) VALUES ('Personalized Gifts');
INSERT INTO tb_category(name) VALUES ('Home Decor');
INSERT INTO tb_category(name) VALUES ('Fashion Accessories');
INSERT INTO tb_category(name) VALUES ('Craft Supplies');
INSERT INTO tb_category(name) VALUES ('Board Games');
INSERT INTO tb_category(name) VALUES ('Virtual Reality');
INSERT INTO tb_category(name) VALUES ('Smart Home Devices');
INSERT INTO tb_category(name) VALUES ('Camping Gear');
INSERT INTO tb_category(name) VALUES ('Cookware & Kitchen Appliances');
INSERT INTO tb_category(name) VALUES ('Educational Toys');
INSERT INTO tb_category(name) VALUES ('Collectibles');
INSERT INTO tb_category(name) VALUES ('Home Office Essentials');
INSERT INTO tb_category(name) VALUES ('Virtual Fitness Classes');
INSERT INTO tb_category(name) VALUES ('Smart Lighting');
INSERT INTO tb_category(name) VALUES ('Board Game Accessories');
INSERT INTO tb_category(name) VALUES ('Augmented Reality');
INSERT INTO tb_category(name) VALUES ('Portable Camping Gear');
INSERT INTO tb_category(name) VALUES ('Bakeware & Cooking Utensils');
INSERT INTO tb_category(name) VALUES ('Interactive Learning Toys');
INSERT INTO tb_category(name) VALUES ('Retro Video Games');
INSERT INTO tb_category(name) VALUES ('Home Security Systems');
INSERT INTO tb_category(name) VALUES ('Maternity & Nursing');
INSERT INTO tb_category(name) VALUES ('Vintage Vinyl Records');
INSERT INTO tb_category(name) VALUES ('Calligraphy Supplies');
INSERT INTO tb_category(name) VALUES ('Drone Photography');
INSERT INTO tb_category(name) VALUES ('Fitness Tracker Accessories');
INSERT INTO tb_category(name) VALUES ('International Cuisine');
INSERT INTO tb_category(name) VALUES ('DIY Craft Kits');
INSERT INTO tb_category(name) VALUES ('Robotics');
INSERT INTO tb_category(name) VALUES ('Virtual Personal Assistants');
INSERT INTO tb_category(name) VALUES ('Customized Home Decor');
